"""
Django settings for nzhome project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path

import environ
from django.conf.locale.es import formats as es_formats

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# CONFIG ENV VARIABLES
env = environ.Env(DEBUG=(bool, False))
environ.Env.read_env()

# DATE FORMAT
es_formats.DATE_FORMAT = "d/m/Y"

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DEBUG")

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    "jet",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "nzhome.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates/")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "nzhome.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    # Descomenta para usar sqlite3
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
    # ------------------------------
    # Descomenta para usar postgresql
    # "default": {
    #    "ENGINE": "django.db.backends.postgresql",
    #    "NAME": env("POSTGRESQL_NAME"),
    #    "USER": env("POSTGRESQL_USER"),
    #    "PASSWORD": env("POSTGRESQL_PASS"),
    #    "HOST": env("POSTGRESQL_HOST"),
    #    "PORT": env("POSTGRESQL_PORT"),
    # }
    # -------------------------------
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/


# ------------- ENGLISH -------------------
LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"
# ----------------------------------------

# ------------ SPANISH --------------------
LANGUAGE_CODE = "es"

LANGUAGES = [
    ("es", "Spanish"),
]

LOCALE_PATHS = [
    os.path.join(BASE_DIR, "locale"),
]


TIME_ZONE = "America/Argentina/Buenos_Aires"
# ---------------------------------------------

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, "public/static")
STATIC_URL = "/public/static/"
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "public/custom_static"),
]

# Directorio de archivos multimedia (imágenes, etc.)
MEDIA_ROOT = os.path.join(BASE_DIR, "public/media")
MEDIA_URL = "/public/media/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# IF YOU HAVE PROBLEMS SAVING A BIG NUMBER OF FIELDS
# DATA_UPLOAD_MAX_NUMBER_FIELDS = 3000

# -------------- JET --------------------------
# Poder ver los modales
X_FRAME_OPTIONS = "SAMEORIGIN"

# Temas de colores para jet
JET_THEMES = [
    {
        "theme": "default",  # theme folder name
        "color": "#47bac1",  # color of the theme's button in user menu
        "title": "Default",  # theme title
    },
    {"theme": "green", "color": "#44b78b", "title": "Green"},
    {"theme": "light-green", "color": "#2faa60", "title": "Light Green"},
    {"theme": "light-violet", "color": "#a464c4", "title": "Light Violet"},
    {"theme": "light-blue", "color": "#5EADDE", "title": "Light Blue"},
    {"theme": "light-gray", "color": "#222", "title": "Light Gray"},
]
# ----------------------------------------------------------------

# --------------------- LOGS -------------------------------------
LOGGING_DIR = os.path.join(BASE_DIR, "logs")  # Ruta al directorio de tu proyecto
DEBUG_LOG_FILE = os.path.join(LOGGING_DIR, "django.log")

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "file": {
            "level": "DEBUG",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": DEBUG_LOG_FILE,
            "maxBytes": 1024 * 1024 * 5,  # Tamaño máximo del archivo de registro: 5 MB
            "backupCount": 5,  # Número de archivos de respaldo
            "formatter": "verbose",
        },
    },
    "root": {
        "handlers": ["file"],
        "level": "DEBUG",
    },
}
# --------------------------------------------------------------------
